IBX-394: Added lazy to registry cronjobs service
ezsystems/ezplatform-cron pull request #21
Opened 2021-05-20 08:06 UTC by mateuszdebinski

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-394](https://issues.ibexa.co/browse/IBX-394)
| **Type**                                   | bug
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no
| **Doc needed**                       | no

After changed ConsoleCommandListener subscription from MVCEvents::CONSOLE_INIT to  ConsoleEvents::COMMAND CronJobsRegistry is not take siteaccess from ConsoleCommandListener

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [x] Checked that target branch is set correctly.

2021-05-20 08:17 UTC, Steveb-p approved these changes
In general I'd personally prefer to have a "Registry" service instead, that I'd be able to call `getCurrentSiteAccess()` on, but that's outside the scope of this PR.

2021-05-20 10:11 UTC, alongosz requested changes
Are you sure 3.0 is still supported? AFAICS Ibexa 3.2 has already 3.1 version of that package. Double check please.

> In general I'd personally prefer to have a "Registry" service instead, that I'd be able to call `getCurrentSiteAccess()` on, but that's outside the scope of this PR.

Actually... I see this is for 3.2. Could you check if  `\eZ\Publish\Core\MVC\Symfony\SiteAccess\SiteAccessServiceInterface::getCurrent` works for you?

2021-05-20 10:48 UTC, Steveb-p commented
> Could you check if `\eZ\Publish\Core\MVC\Symfony\SiteAccess\SiteAccessServiceInterface::getCurrent` works for you?

If this service could be used instead of marking the console command as lazy, that would be my go to solution. Lazy services are a workaround in this case for using a property that changes on runtime, and it does not work 100% of the time since it can change more than once, after initialization of the proxy.

2021-05-20 10:53 UTC, mateuszdebinski commented
I changed the branch to 3.1 because IBEXA 3.2 works fine only in 3.3 is a problem. I will add this service to `CronJobsRegistry` and check

2021-05-20 11:23 UTC, mateuszdebinski commented
`\eZ\Publish\Core\MVC\Symfony\SiteAccess\SiteAccessServiceInterface::getCurrent` not working always return "default" like now

2021-05-20 11:35 UTC, Steveb-p commented
> `\eZ\Publish\Core\MVC\Symfony\SiteAccess\SiteAccessServiceInterface::getCurrent` not working always return "default" like now

That's kinda bad. It should update just like the container updates :confused:

2021-05-20 11:45 UTC, alongosz commented
> > `\eZ\Publish\Core\MVC\Symfony\SiteAccess\SiteAccessServiceInterface::getCurrent` not working always return "default" like now
> 
> That's kinda bad. It should update just like the container updates

@Steveb-p after further debugging I see the method which requires SA name is used when building a Container via `addMethodCall`. To fix that, every cron-executed command would need to fetch the information on its own, which is not possible. Let me know if you think I'm missing something.

2021-05-20 12:22 UTC, Steveb-p commented
> To fix that, every cron-executed command would need to fetch the information on its own, which is not possible. Let me know if you think I'm missing something.

I have no idea how specifically this package works, so if it's a bugfix and other than that it works as designed, then I don't mind it going like this.

2021-05-21 09:08 UTC, bogusez approved these changes

2021-05-21 09:13 UTC, merged